### ISSUE TITLE
Minimal Example in Readme.MD

### ISSUE THREAD

**Issue by ajaychawda58** [egolinko/qgel#1]
I guess the existing example 

`embedding, vectors, source_data_ = qgel.qgel(source_data_ = X,
                                             k = 10,
                                             learning_method = 'supervised',
                                             class_var = "Class"
                                        )`

should be modified to

`embedding, vectors, one_hot_data = qgel.qgel(one_hot_data = X,
                                             k = 10,
                                             learning_method = 'supervised',
                                             class_var = "Class"
                                        )`

**Comment by egolinko** [comment]
I've updated, thank you for the suggestion @ajaychawda58 .
